GROQ_API="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"
LANGSMITH_TRACING="true"
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="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"
LANGSMITH_PROJECT="pg_agi"